version: '3'

services:
  zookeeper:
    build: ./broker/zookeeper
    image: psmiraglia/elk/broker/zookeeper
  kafka:
    build: ./broker/kafka
    image: psmiraglia/elk/broker/kafka
    depends_on:
      - zookeeper
    links:
      - zookeeper:zookeeper
    environment:
      - ZK_HOST=zookeeper
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.2
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.1.2
    depends_on:
      - elasticsearch
    links:
      - elasticsearch:elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - 5601:5601
