version: '3'

services:
  zookeeper:
    build: ./broker/zookeeper
    image: psmiraglia/elk/broker/zookeeper
  kafka:
    build: ./broker/kafka
    image: psmiraglia/elk/broker/kafka
    depends_on:
      - zookeeper
    links:
      - zookeeper:zookeeper
    environment:
      - ZK_HOST=zookeeper
  logstash:
    build: ./indexer/logstash
    image: psmiraglia/elk/indexer/logstash
    depends_on:
      - elasticsearch
    links:
      - elasticsearch:elasticsearch
      - kafka:kafka
  metricbeat:
    build: ./shipper/metricbeat
    image: psmiraglia/elk/shipper/metricbeat
    depends_on:
      - kafka
    links:
      - kafka:kafka
