metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

processors:
- add_cloud_metadata:

output.redis:
  enabled: true
  hosts: ['redis:6379']
  key: 'metricbeat'
  datatype: 'list'
